#
# https://wiki.debian.org/UnattendedUpgrades
#
- name: Send emails for unattended upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^Unattended-Upgrade::Mail '
    insertafter: '^//Unattended-Upgrade::Mail '
    line: 'Unattended-Upgrade::Mail "root";'

- name: Automatically call unattended upgrades
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";